# Generated by Django 3.2.20 on 2023-08-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perros'),
        ),
    ]
