# Generated by Django 3.2.20 on 2023-08-06 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perros', '0003_auto_20230805_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perro',
            options={'ordering': ['creador', '-foto']},
        ),
        migrations.AlterField(
            model_name='perro',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
