# Generated by Django 3.2.20 on 2023-08-06 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0004_auto_20230806_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perro',
            options={'ordering': ['usuario', '-foto']},
        ),
        migrations.RenameField(
            model_name='perro',
            old_name='creador',
            new_name='usuario',
        ),
    ]
